highlighter: rouge
github: [Repository metadata]

markdown: kramdown

paginate: 8 

sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

# Gems
gems: [jekyll-paginate]
